CREATE TABLE USUARIO(
ID BIGINT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
REMETENTE VARCHAR(100) NOT NULL,
DESTINATARIO VARCHAR(100) NOT NULL
);


CREATE TABLE TIPO_DE_ENVIO(
IDENTIFICADOR BIGINT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL
);

CREATE TABLE ITEM(
CODIGO BIGINT PRIMARY KEY,
TIPO VARCHAR(100) NOT NULL,
TAMANHO NUMERIC(8,2) NOT NULL,
PESO NUMERIC(8,2) NOT NULL,
ID BIGINT NOT NULL,
IDENTIFICADOR BIGINT NOT NULL,
FOREIGN KEY(ID) REFERENCES USUARIO,
FOREIGN KEY(IDENTIFICADOR) REFERENCES TIPO_DE_ENVIO
);